
namespace SmartTouch.CRM.Web.Utilities
{
    public enum MenuCategory : byte
    {
        Undefined = 0,
        Contacts = 1,
        ContactAction = 2,
        CompanyAction = 3,
        AccountAddAction = 4,
        AccountEditAction = 5,
        Accounts = 6,
        UsersEdiAction = 7,
        Users = 8,
        Campaigns = 9,
        AddCampaign = 10,
        LeadScore = 11,
        ManageTags = 12,
        Forms = 13,
        Settings = 14,
        DropdownFields=15,
        LeadAdapters = 31,
        AddEditLeadAdapter = 37,
        ImportData = 16,
        AccountSettings = 17,
        AddEditForm = 36,
        Opportunities = 40,
        AddEditOpportunity = 41,
        ViewOpportunity = 42,
        LeftMenuCRM = 43,
        LeftMenuAccountConfiguration = 44,
        LeftMenuAccountSettings = 45,
        CustomFields = 53,
        Roles = 52,
        AdvancedSearch = 54,
        AdvancedSearchList = 55,
        SaveSettings = 56,
        EmptyTopMenuItem = 57,
        EditCampaign = 58,
        CampaignStatistics = 59,
        Automation = 60,
        EditWorkflow = 61,
        AddWorkflow = 62,
        Dashboard=63,
        Reports=64,
        EditReport=65,
        ViewWorkflow = 66,
        ImportDataStep2 = 67,
        RolesList = 68,
        ActionList = 69,
        ImageDomain= 70,
        SeedList = 71,
        ApiKeys =82,
        MarketingMessageCenter = 83,
        MarketingMessage = 84,
        TourCMS = 85,
        FormSubmissions = 88,
        ContactEngagementSummary =89,
        SuppressionList = 90,
        NeverBounce = 91, //NeverBounce
        EmailValidator = 92 //EmailValidator for NeverBounce
    }
}