//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace htmlreader
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int ImageID { get; set; }
        public string FriendlyName { get; set; }
        public Nullable<int> AccountID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public byte ImageCategoryID { get; set; }
        public string OriginalName { get; set; }
        public string StorageName { get; set; }
    }
}
