//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace htmlreader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartCRMLoadTestEntities : DbContext
    {
        public SmartCRMLoadTestEntities()
            : base("name=SmartCRMLoadTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<CampaignLinks> CampaignLinks { get; set; }
        public virtual DbSet<ClassicCampaigns> ClassicCampaigns { get; set; }
        public virtual DbSet<Campaigns> Campaigns { get; set; }
    }
}
