
CREATE procedure [dbo].[Sp_insert_Default_preconfig_searches]
as 
begin

DECLARE @SDID INT
DECLARE @DROPDOWNVALUEID smallInt
DECLARE @ACCOUNTID INT
DECLARE @CREATEDBY INT
DECLARE @error_num int


Begin Try

SELECT @ACCOUNTID = MIN(ACCOUNTID) FROM ACCOUNTS (NOLOCK)
  Begin TRANSACTION
WHILE(@ACCOUNTID IS NOT NULL)
       BEGIN
	  
                     SELECT @CREATEDBY = CREATEDBY FROM ACCOUNTS WHERE ACCOUNTID = @ACCOUNTID 
                     --CALL LIST:
                     INSERT INTO SEARCHDEFINITIONS(SEARCHDEFINITIONNAME,SEARCHPREDICATETYPEID,CUSTOMPREDICATESCRIPT,ELASTICQUERY,  ACCOUNTID, CREATEDBY, CREATEDON, ISPRECONFIGUREDSEARCH, ISFAVORITESEARCH, LASTRUNDATE)
                     VALUES ('CALL LIST', 2, '1 OR 2 OR 3', NULL, @ACCOUNTID, @CREATEDBY, GETUTCDATE() , 1, 0,NULL)
			
 
                     SELECT @SDID = SCOPE_IDENTITY()
                     SELECT @DROPDOWNVALUEID = DROPDOWNVALUEID FROM DROPDOWNVALUES(NOLOCK) WHERE ACCOUNTID = @ACCOUNTID AND DROPDOWNVALUETYPEID = 9
 
                     INSERT INTO SEARCHFILTERS(FIELDID, SEARCHQUALIFIERTYPEID, SEARCHTEXT, SEARCHDEFINITIONID, DROPDOWNVALUEID)
                     VALUES(NULL, 4, '', @SDID, @DROPDOWNVALUEID)
 
                     SELECT @DROPDOWNVALUEID = DROPDOWNVALUEID FROM DROPDOWNVALUES WHERE ACCOUNTID = @ACCOUNTID AND DROPDOWNVALUETYPEID = 10
                     INSERT INTO SEARCHFILTERS(FIELDID, SEARCHQUALIFIERTYPEID, SEARCHTEXT, SEARCHDEFINITIONID, DROPDOWNVALUEID)
                     VALUES(NULL, 4, '', @SDID, @DROPDOWNVALUEID)
 
                     SELECT @DROPDOWNVALUEID = DROPDOWNVALUEID FROM DROPDOWNVALUES WHERE ACCOUNTID = @ACCOUNTID AND DROPDOWNVALUETYPEID = 11
                     INSERT INTO SEARCHFILTERS(FIELDID, SEARCHQUALIFIERTYPEID, SEARCHTEXT, SEARCHDEFINITIONID, DROPDOWNVALUEID)
                     VALUES(NULL, 4, '', @SDID, @DROPDOWNVALUEID)
 
                     --EMAIL LIST:
                     INSERT INTO SEARCHDEFINITIONS(SEARCHDEFINITIONNAME,SEARCHPREDICATETYPEID,CUSTOMPREDICATESCRIPT,ELASTICQUERY,  ACCOUNTID, CREATEDBY, CREATEDON,ISPRECONFIGUREDSEARCH,ISFAVORITESEARCH, LASTRUNDATE)
                     VALUES ('EMAIL LIST', 2, '1', NULL, @ACCOUNTID, @CREATEDBY, GETUTCDATE(), 1, 0, NULL)
 
                     SELECT @SDID = SCOPE_IDENTITY()
                    
                     INSERT INTO SEARCHFILTERS(FIELDID,SEARCHQUALIFIERTYPEID,SEARCHTEXT,SEARCHDEFINITIONID,DROPDOWNVALUEID)
                     VALUES(7, 4,'', @SDID, NULL)
 
                     --STAGE REPORT:
                     INSERT INTO SEARCHDEFINITIONS(SEARCHDEFINITIONNAME,SEARCHPREDICATETYPEID,CUSTOMPREDICATESCRIPT,ELASTICQUERY,  ACCOUNTID, CREATEDBY, CREATEDON,ISPRECONFIGUREDSEARCH,ISFAVORITESEARCH, LASTRUNDATE)
                     VALUES ('STAGE REPORT', 1, '1', NULL, @ACCOUNTID, @CREATEDBY, GETUTCDATE(), 1, 0, NULL)
 
                     SELECT @SDID = SCOPE_IDENTITY()
                     SELECT @DROPDOWNVALUEID = DROPDOWNVALUEID FROM DROPDOWNVALUES(NOLOCK) WHERE ACCOUNTID = @ACCOUNTID AND DROPDOWNVALUETYPEID = 15
 
                     INSERT INTO SEARCHFILTERS(FIELDID,SEARCHQUALIFIERTYPEID,SEARCHTEXT,SEARCHDEFINITIONID,DROPDOWNVALUEID)
                     VALUES(22, 1,CAST(@DROPDOWNVALUEID as varchar(150)), @SDID, NULL)

				
 
                     SELECT @ACCOUNTID = MIN(ACCOUNTID) FROM ACCOUNTS WHERE ACCOUNTID > @ACCOUNTID
       END
	  	 Commit Transaction  
End Try 
Begin Catch
 IF @@TRANCOUNT > 0

       ROLLBACK TRANSACTION
      
  
    SELECT
             ERROR_NUMBER() AS ErrorNumber
            ,ERROR_SEVERITY() AS ErrorSeverity
            ,ERROR_STATE() AS ErrorState
            ,ERROR_PROCEDURE() AS ErrorProcedure
            ,ERROR_LINE() AS ErrorLine
            ,ERROR_MESSAGE() AS ErrorMessage
            ,GETDATE()
End Catch


 end


GO


