
CREATE PROCEDURE [dbo].[Get_Account_HotListContacts_Report]
	(
		@ACCOUNTID		INT,
		@FROMDATE       DATETIME,
		@TODATE         DATETIME,
		@OWNERID		VARCHAR(MAX),
		@LIFECYCLESTAGE VARCHAR(MAX)--,
		--@LIMIT			INT =10
	)
AS 
BEGIN
	--SET NOCOUNT ON
	--BEGIN TRY
		SELECT * FROM (SELECT ROW_NUMBER() OVER (ORDER BY ISNULL(L.NEWPOINTS,0) DESC) as ROWNUM, C.CONTACTID AS CONTACTID, (ISNULL(C.FIRSTNAME, '') + ' ' + ISNULL(C.LASTNAME, '')) AS [FULLNAME],
			(ISNULL(U.FIRSTNAME, '') + ' ' + ISNULL(U.LASTNAME, '')) AS [ACCOUNTEXEC],
			DDV.DROPDOWNVALUE AS LEADSOURCE ,
			DDV1.DROPDOWNVALUE AS LIFECYCLE ,
			CE.EMAIL [EMAIL], 
			CE.EMAILSTATUS [EMAILSTATUS], 
			CE.CONTACTEMAILID [CONTACTEMAILID],
			CPN.PHONENUMBER [PHONENUMBER], 
			CPN.CONTACTPHONENUMBERID [CONTACPHONENUMBERID],
			ISNULL(L.LEADSCORE,0) AS LEADSCORE, 
			ISNULL(L.NEWPOINTS,0) AS NEWPOINTS
			FROM CONTACTS(NOLOCK) C 
			INNER JOIN  CONTACTLEADSOURCEMAP(NOLOCK) CLS ON CLS.CONTACTID = C.CONTACTID AND ISPRIMARYLEADSOURCE = 1 
			INNER JOIN DROPDOWNVALUES(NOLOCK) DDV ON DDV.DROPDOWNVALUEID = CLS.LEADSOUCEID
			INNER JOIN DROPDOWNVALUES(NOLOCK) DDV1 ON DDV1.DROPDOWNVALUEID = C.LIFECYCLESTAGE 
			LEFT JOIN USERS(NOLOCK) U ON U.ACCOUNTID IN (C.ACCOUNTID, 1) AND C.OWNERID = U.USERID
			LEFT JOIN CONTACTEMAILS(NOLOCK) CE ON CE.CONTACTID = C.CONTACTID AND CE.ISPRIMARY = 1
			LEFT JOIN CONTACTPHONENUMBERS(NOLOCK) CPN ON CPN.CONTACTID = C.CONTACTID  AND CPN.ISPRIMARY = 1
			CROSS APPLY DBO.GETLEADSCORE(C.CONTACTID, @FROMDATE, @TODATE) L
			WHERE C.ACCOUNTID = @ACCOUNTID	AND C.ISDELETED = 0
			AND DDV1.DROPDOWNVALUEID IN (SELECT DATAVALUE FROM DBO.SPLIT(@LIFECYCLESTAGE ,','))
			AND (C.OWNERID IN (SELECT DATAVALUE FROM DBO.SPLIT(@OWNERID ,',')) OR C.OWNERID IS NULL)
			AND C.LIFECYCLESTAGE IN (SELECT DATAVALUE FROM DBO.SPLIT(@LIFECYCLESTAGE ,','))
			AND CONVERT(VARCHAR(10), C.LastUpdatedOn, 110) BETWEEN @FROMDATE AND @TODATE) N
			--WHERE N.ROWNUM <= @LIMIT		
	--END TRY
	--BEGIN CATCH
	--	SELECT 'SEL-002' RESULTCODE

	--	INSERT INTO DBO.IMPORTCONTACTLOGS (USERNAME, ERRORNUMBER, ERRORSEVERITY, ERRORSTATE, ERRORPROCEDURE, ERRORLINE, ERRORMESSAGE, LOGDATE)
	--	VALUES (CONVERT(SYSNAME, CURRENT_USER), ERROR_NUMBER(), ERROR_SEVERITY(), ERROR_STATE(), ERROR_PROCEDURE(), ERROR_LINE(), ERROR_MESSAGE(), GETUTCDATE())
	--END CATCH
	--SET NOCOUNT OFF
END

/*
	  EXEC [DBO].[GET_ACCOUNT_HOTLISTCONTACTS_REPORT]
		 @ACCOUNTID			= 4218,
		 @FROMDATE          = '2015-02-07 00:00:00.000',       
		 @TODATE            = '2015-03-09 00:00:00.000',
		 @OWNERID			= '5493,5497,5505,6518,6535,6574,6604,6608,6799,6800,6802,6803,6809,6822,6834,6842,6849,6868,6869,6876,6877,6882,6883,6885,6886,6887,6889,6890,6891,6895,6907,6909',
		 @LIFECYCLESTAGE    = '4663,4664,4665,4676,4677'

*/