CREATE TABLE [dbo].[BulkContactData] (
    [BulkContactDataID] INT IDENTITY (1, 1) NOT NULL,
    [BulkOperationID]   INT NOT NULL,
    [ContactID]         INT NOT NULL,
    CONSTRAINT [PK_BulkContactData] PRIMARY KEY CLUSTERED ([BulkContactDataID] ASC) WITH (FILLFACTOR = 90)
);
go

CREATE NONCLUSTERED INDEX [IX_BulkContactData_missing_437] ON [dbo].[BulkContactData]
(
	[BulkOperationID] ASC
)
INCLUDE ( 	[ContactID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

