//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace htmlreader
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignLinks
    {
        public int CampaignLinkID { get; set; }
        public int CampaignID { get; set; }
        public string URL { get; set; }
        public byte LinkIndex { get; set; }
        public string Name { get; set; }
    
        public virtual Campaigns Campaigns { get; set; }
    }
}
