//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace htmlreader
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaigns
    {
        public Campaigns()
        {
            this.CampaignLinks = new HashSet<CampaignLinks>();
        }
    
        public int CampaignID { get; set; }
        public short CampaignStatusID { get; set; }
        public int CampaignTemplateID { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public string HTMLContent { get; set; }
        public Nullable<System.DateTime> ScheduleTime { get; set; }
        public string From { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ServiceProviderID { get; set; }
        public bool IsDeleted { get; set; }
        public int AccountID { get; set; }
        public string SenderName { get; set; }
        public string ServiceProviderCampaignID { get; set; }
        public string Remarks { get; set; }
        public string LastViewedState { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public bool IsLinkedToWorkflows { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public Nullable<short> TagRecipients { get; set; }
        public Nullable<short> SSRecipients { get; set; }
    
        public virtual ICollection<CampaignLinks> CampaignLinks { get; set; }
    }
}
