CREATE FUNCTION [dbo].[GetLeadScore](@CONTACTID INT, @FROMDATE DATETIME, @TODATE DATETIME)
RETURNS TABLE AS
RETURN	
(
	WITH SCORE_CTE(CONTACTID, LEADSCORE)
	AS
	(
		SELECT CONTACTID, SUM(SCORE) AS LEADSCORE FROM LEADSCORES WHERE CONTACTID = @CONTACTID 	
		GROUP BY CONTACTID
	)

	SELECT TOP 1 L.CONTACTID, S.LEADSCORE, SUM(L.SCORE) AS NEWPOINTS FROM LEADSCORES L INNER JOIN SCORE_CTE S ON S.CONTACTID = L.CONTACTID
	WHERE  L.CONTACTID = @CONTACTID AND CONVERT(VARCHAR(10), L.ADDEDON, 110) BETWEEN @FROMDATE AND @TODATE
	GROUP BY L.CONTACTID,S.LEADSCORE
)




