CREATE TYPE [dbo].[AccountInfo] AS TABLE (
    [AccountID]            INT            NULL,
    [AccountName]          NVARCHAR (75)  NULL,
    [FirstName]            NVARCHAR (75)  NULL,
    [LastName]             NVARCHAR (75)  NULL,
    [Company]              NVARCHAR (75)  NULL,
    [PrimaryEmail]         VARCHAR (256)  NULL,
    [HomePhone]            VARCHAR (20)   NULL,
    [WorkPhone]            VARCHAR (20)   NULL,
    [MobilePhone]          VARCHAR (20)   NULL,
    [PrivacyPolicy]        VARCHAR (MAX)  NULL,
    [SubscriptionID]       TINYINT        NULL,
    [DateFormatID]         TINYINT        NULL,
    [CurrencyID]           TINYINT        NULL,
    [CountryID]            NCHAR (2)      NULL,
    [TimeZone]             VARCHAR (32)   NULL,
    [Status]               TINYINT        NULL,
    [CreatedBy]            INT            NULL,
    [CreatedOn]            DATETIME       NULL,
    [ModifiedBy]           INT            NULL,
    [ModifiedOn]           DATETIME       NULL,
    [DomainURL]            VARCHAR (100)  NULL,
    [FacebookUrl]          VARCHAR (200)  NULL,
    [TwitterUrl]           VARCHAR (200)  NULL,
    [GooglePlusUrl]        VARCHAR (200)  NULL,
    [LinkedInUrl]          VARCHAR (200)  NULL,
    [BlogUrl]              VARCHAR (200)  NULL,
    [WebSiteUrl]           VARCHAR (200)  NULL,
    [GoogleDriveAPIKey]    NVARCHAR (200) NULL,
    [GoogleDriveClientID]  NVARCHAR (200) NULL,
    [OpportunityCustomers] TINYINT        NULL,
    [DropboxAppKey]        NVARCHAR (200) NULL,
    [FacebookAPPID]        VARCHAR (MAX)  NULL,
    [FacebookAPPSecret]    VARCHAR (MAX)  NULL,
    [TwitterAPIKey]        VARCHAR (MAX)  NULL,
    [TwitterAPISecret]     VARCHAR (MAX)  NULL,
    [StatusMessage]        NVARCHAR (MAX) NULL,
    [HelpURL]              VARCHAR (500)  NOT NULL,
    [ShowTC]               BIT            NOT NULL,
    [TC]                   NVARCHAR (MAX) NULL,
    [UserLimit]            INT            NULL,
    [ExcludedRoles]        NVARCHAR (100) NULL);

