CREATE TYPE [dbo].[ContactType] AS TABLE (
    [ContactID]            INT              NULL,
    [FirstName]            NVARCHAR (200)   NULL,
    [LastName]             NVARCHAR (200)   NULL,
    [Company]              NVARCHAR (200)   NULL,
    [CommunicationID]      INT              NULL,
    [Title]                NVARCHAR (300)   NULL,
    [ContactImageUrl]      VARCHAR (2000)   NULL,
    [AccountID]            INT              NULL,
    [LeadSource]           NVARCHAR (100)   NULL,
    [HomePhone]            VARCHAR (75)     NULL,
    [WorkPhone]            VARCHAR (75)     NULL,
    [MobilePhone]          VARCHAR (75)     NULL,
    [PrimaryEmail]         VARCHAR (300)    NULL,
    [ContactType]          TINYINT          NULL,
    [SSN]                  VARCHAR (300)    NULL,
    [LifecycleStage]       SMALLINT         NULL,
    [DoNotEmail]           BIT              NULL,
    [LastContacted]        DATETIME         NULL,
    [IsDeleted]            BIT              NULL,
    [ProfileImageKey]      UNIQUEIDENTIFIER NULL,
    [ImageID]              INT              NULL,
    [ReferenceID]          UNIQUEIDENTIFIER NULL,
    [LastUpdatedBy]        INT              NULL,
    [LastUpdatedOn]        DATETIME         NULL,
    [OwnerID]              INT              NULL,
    [PartnerType]          SMALLINT         NULL,
    [ContactSource]        TINYINT          NULL,
    [SourceType]           INT              NULL,
    [CompanyID]            INT              NULL,
    [LastContactedThrough] TINYINT          NULL,
    [FirstContactSource]   TINYINT          NULL,
    [FirstSourceType]      INT              NULL,
    [LeadScore]            INT              NULL,
    [IncludeInReports]     BIT              NULL);

