CREATE TYPE [dbo].[IMPORT_ContactDetails] AS TABLE (
    [FirstName]                 NVARCHAR (75)    NULL,
    [LastName]                  NVARCHAR (75)    NULL,
    [CompanyName]               NVARCHAR (75)    NULL,
    [Title]                     NVARCHAR (100)   NULL,
    [LeadSource]                NVARCHAR (100)   NULL,
    [LifecycleStage]            VARCHAR (50)     NULL,
    [PartnerType]               VARCHAR (50)     NULL,
    [DoNotEmail]                BIT              NULL,
    [HomePhone]                 VARCHAR (20)     NULL,
    [MobilePhone]               VARCHAR (20)     NULL,
    [WorkPhone]                 VARCHAR (20)     NULL,
    [AccountID]                 INT              NULL,
    [PrimaryEmail]              VARCHAR (256)    NULL,
    [SecondaryEmails]           NVARCHAR (2100)  NULL,
    [FacebookUrl]               NVARCHAR (2000)  NULL,
    [TwitterUrl]                NVARCHAR (2000)  NULL,
    [GooglePlusUrl]             NVARCHAR (2000)  NULL,
    [LinkedInUrl]               NVARCHAR (2000)  NULL,
    [BlogUrl]                   NVARCHAR (2000)  NULL,
    [WebSiteUrl]                NVARCHAR (2000)  NULL,
    [AddressLine1]              VARCHAR (95)     NULL,
    [AddressLine2]              VARCHAR (95)     NULL,
    [City]                      VARCHAR (35)     NULL,
    [State]                     NVARCHAR (64)    NULL,
    [Country]                   NVARCHAR (64)    NULL,
    [ZipCode]                   VARCHAR (11)     NULL,
    [IsDefault]                 BIT              NULL,
    [ImportDataId]              INT              NULL,
    [LeadAdapterRecordStatusId] INT              NULL,
    [ReferenceId]               UNIQUEIDENTIFIER NULL,
    [ContactID]                 INT              NULL,
    [IsDeleted]                 BIT              NULL,
    [BuilderNumber]             NVARCHAR (75)    NULL,
    [CustomFieldsData]          NVARCHAR (MAX)   NULL,
    [PhoneData]                 NVARCHAR (2000)  NULL,
    [Emails]                    NVARCHAR (2000)  NULL,
    [ContactType]               TINYINT          NULL,
    [EmailStatus]               SMALLINT         NULL);

